version: "3.9"
services:
  postgres:
    image: postgres:13.2
    restart: always
    environment:
      POSTGRES_PASSWORD: inventory
  redis:
    image: redis:5.0.9
    restart: always
  inventory:
    image: inventory
    restart: always
    environment:
      INVENTORY_PGL_CONNECTION_STRING: host=postgres user=postgres password=inventory dbname=postgres port=9920 sslmode=disable TimeZone=America/Los_Angeles
    depends_on:
      - postgres
      - redis
    volumes:
      - type: volume
        source: inventory-log
        target: /app/log
volumes:
  inventory-log: